[package]
name = "aoc22-13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hymns = { workspace = true }
nom = { workspace = true }
itertools = { workspace = true }


[lints]
workspace = true
