repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: rustfmt
        entry: cargo fmt --
        language: system
        files: \.rs$
      - id: clippy
        name: clippy
        description: clippy
        entry: cargo clippy -q
        language: system
        files: \.rs$
        pass_filenames: false
        require_serial: true
        verbose: true
