[package]
name = "aoc20-12"
version = "0.1.0"
authors = ["Justin Prieto <justin@prieto.nyc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hymns = { workspace = true }

[lints]
workspace = true
